[package]
name = "ex07"
version = "0.1.0"
authors = ["k0pernicus"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_helper = { path = "../../aoc_helper", version = "0.1.0" }
lazy_static = "1.4.0"
regex = "1.4.2"
